# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bbab9f2034c0f772af1ae487b7212a76808d58ddbe48e1f122745ab233c6b30e90b9471847f5b8d3ad212e62ddefe8c8a22df0f366522fac7d38a0d639c5623

test:
  secret_key_base: a6cc320a3e69257875e0c0beb02c0898c43c4be20797257706ff87de45e9ccf23ba56438c4a0264d203eaeb15e0bf5c34ad01a7238ea298cb4f831b1690acf8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
